version: 1.0

period: 10 #扫描周期单位(s)

github:
  repos_api: https://api.github.com/search/repositories #github search api
  query: CVE-2021 #搜索的cve关键字

mail: #消息提醒邮件设置
  host: smtp.163.com
  port: 25
  username: xxx@163.com
  password: xxxx
  from: xxxx
  to: "xxx@126.com"
